// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgBh56gf8a-VATX1YUEKjkH2-BWV8dal4',
    appId: '1:558528413385:web:dda79a3805baaf854c1718',
    messagingSenderId: '558528413385',
    projectId: 'income-app-2a2aa',
    authDomain: 'income-app-2a2aa.firebaseapp.com',
    storageBucket: 'income-app-2a2aa.firebasestorage.app',
    measurementId: 'G-KNJ4B7W4PG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVYpLSKTegUsrRYu36qI6cGipH8x8QW7k',
    appId: '1:558528413385:android:fdc1fa5d8a5449ae4c1718',
    messagingSenderId: '558528413385',
    projectId: 'income-app-2a2aa',
    storageBucket: 'income-app-2a2aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq8rgCDDgrZ-OEqvPl92mnN3XL6I997ho',
    appId: '1:558528413385:ios:a5cda2184329b6914c1718',
    messagingSenderId: '558528413385',
    projectId: 'income-app-2a2aa',
    storageBucket: 'income-app-2a2aa.firebasestorage.app',
    iosBundleId: 'com.example.projectIncomeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq8rgCDDgrZ-OEqvPl92mnN3XL6I997ho',
    appId: '1:558528413385:ios:a5cda2184329b6914c1718',
    messagingSenderId: '558528413385',
    projectId: 'income-app-2a2aa',
    storageBucket: 'income-app-2a2aa.firebasestorage.app',
    iosBundleId: 'com.example.projectIncomeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgBh56gf8a-VATX1YUEKjkH2-BWV8dal4',
    appId: '1:558528413385:web:efa37f67aa87cf254c1718',
    messagingSenderId: '558528413385',
    projectId: 'income-app-2a2aa',
    authDomain: 'income-app-2a2aa.firebaseapp.com',
    storageBucket: 'income-app-2a2aa.firebasestorage.app',
    measurementId: 'G-T67D7ZC5YP',
  );
}
